# 마인드 싱크(Mind Sync) 게임용 단어 리스트
# 총 1,000개의 추상적, 현대적, 감각적 단어들로 구성되었습니다.

WORD_POOL = [
    # 1. 감정과 심리 상태 (200개)
    {"ko": "그리움", "en": "Longing"}, {"ko": "설렘", "en": "Flutter"}, {"ko": "공포", "en": "Fear"}, {"ko": "환희", "en": "Joy"}, {"ko": "우울", "en": "Depression"}, 
    {"ko": "갈망", "en": "Craving"}, {"ko": "평온", "en": "Serenity"}, {"ko": "분노", "en": "Anger"}, {"ko": "질투", "en": "Jealousy"}, {"ko": "동경", "en": "Admiration"},
    {"ko": "고독", "en": "Solitude"}, {"ko": "허무", "en": "Emptiness"}, {"ko": "안도", "en": "Relief"}, {"ko": "연민", "en": "Compassion"}, {"ko": "경외", "en": "Awe"}, 
    {"ko": "후회", "en": "Regret"}, {"ko": "희망", "en": "Hope"}, {"ko": "절망", "en": "Despair"}, {"ko": "혼란", "en": "Confusion"}, {"ko": "확신", "en": "Certainty"},
    {"ko": "자괴감", "en": "Shame"}, {"ko": "자부심", "en": "Pride"}, {"ko": "시기", "en": "Envy"}, {"ko": "용기", "en": "Courage"}, {"ko": "비겁", "en": "Cowardice"}, 
    {"ko": "냉소", "en": "Cynicism"}, {"ko": "열정", "en": "Passion"}, {"ko": "권태", "en": "Boredom"}, {"ko": "호기심", "en": "Curiosity"}, {"ko": "의심", "en": "Doubt"},
    {"ko": "신뢰", "en": "Trust"}, {"ko": "배신감", "en": "Betrayal"}, {"ko": "서운함", "en": "Disappointment"}, {"ko": "벅참", "en": "Overwhelmed"}, {"ko": "애틋함", "en": "Affection"}, 
    {"ko": "담담함", "en": "Calmness"}, {"ko": "조급함", "en": "Impatience"}, {"ko": "여유", "en": "Ease"}, {"ko": "긴장", "en": "Tension"}, {"ko": "공허", "en": "Void"},
    {"ko": "충만", "en": "Fulfillment"}, {"ko": "수줍음", "en": "Shyness"}, {"ko": "대담함", "en": "Boldness"}, {"ko": "증오", "en": "Hatred"}, {"ko": "사랑", "en": "Love"}, 
    {"ko": "미련", "en": "Lingering affection"}, {"ko": "상실", "en": "Loss"}, {"ko": "집착", "en": "Obsession"}, {"ko": "해방감", "en": "Liberation"}, {"ko": "압박감", "en": "Pressure"},
    {"ko": "무기력", "en": "Lethargy"}, {"ko": "활력", "en": "Vitality"}, {"ko": "슬픔", "en": "Sadness"}, {"ko": "기쁨", "en": "Happiness"}, {"ko": "노여움", "en": "Wrath"}, 
    {"ko": "즐거움", "en": "Enjoyment"}, {"ko": "괴로움", "en": "Distress"}, {"ko": "외로움", "en": "Loneliness"}, {"ko": "괴리감", "en": "Discrepancy"}, {"ko": "소속감", "en": "Belonging"},
    {"ko": "유대감", "en": "Bond"}, {"ko": "단절", "en": "Disconnection"}, {"ko": "소외", "en": "Alienation"}, {"ko": "갈등", "en": "Conflict"}, {"ko": "화해", "en": "Reconciliation"}, 
    {"ko": "용서", "en": "Forgiveness"}, {"ko": "원망", "en": "Resentment"}, {"ko": "기다림", "en": "Waiting"}, {"ko": "망설임", "en": "Hesitation"}, {"ko": "결단", "en": "Decision"},
    {"ko": "인내", "en": "Patience"}, {"ko": "체념", "en": "Resignation"}, {"ko": "낙심", "en": "Discouragement"}, {"ko": "환멸", "en": "Disillusionment"}, {"ko": "매혹", "en": "Allure"}, 
    {"ko": "혐오", "en": "Disgust"}, {"ko": "불만", "en": "Dissatisfaction"}, {"ko": "만족", "en": "Satisfaction"}, {"ko": "평화", "en": "Peace"}, {"ko": "혼돈", "en": "Chaos"},
    {"ko": "고요", "en": "Silence"}, {"ko": "소란", "en": "Commotion"}, {"ko": "불안", "en": "Anxiety"}, {"ko": "안정", "en": "Stability"}, {"ko": "신비", "en": "Mystery"}, 
    {"ko": "경계", "en": "Boundary"}, {"ko": "개방", "en": "Openness"}, {"ko": "폐쇄", "en": "Closure"}, {"ko": "억압", "en": "Oppression"}, {"ko": "자유", "en": "Freedom"},
    {"ko": "구속", "en": "Restraint"}, {"ko": "갈증", "en": "Thirst"}, {"ko": "포만", "en": "Satiety"}, {"ko": "결핍", "en": "Deficiency"}, {"ko": "과잉", "en": "Excess"}, 
    {"ko": "고통", "en": "Pain"}, {"ko": "쾌락", "en": "Pleasure"}, {"ko": "숭고", "en": "Sublime"}, {"ko": "비참", "en": "Misery"}, {"ko": "초조", "en": "Nervousness"},
    {"ko": "느긋함", "en": "Relaxation"}, {"ko": "아쉬움", "en": "Regretfulness"}, {"ko": "뿌듯함", "en": "Proud"}, {"ko": "허탈", "en": "Dejection"}, {"ko": "황홀", "en": "Ecstasy"}, 
    {"ko": "무심", "en": "Indifference"}, {"ko": "섬세", "en": "Delicacy"}, {"ko": "예민", "en": "Sensitivity"}, {"ko": "둔감", "en": "Insensitivity"}, {"ko": "집요", "en": "Persistence"},
    {"ko": "방황", "en": "Wandering"}, {"ko": "안착", "en": "Settlement"}, {"ko": "방관", "en": "Bystander"}, {"ko": "참여", "en": "Participation"}, {"ko": "소망", "en": "Wish"}, 
    {"ko": "야망", "en": "Ambition"}, {"ko": "탐욕", "en": "Greed"}, {"ko": "절제", "en": "Moderation"}, {"ko": "친밀", "en": "Intimacy"}, {"ko": "소원", "en": "Desire"},
    {"ko": "어색", "en": "Awkwardness"}, {"ko": "익숙", "en": "Familiarity"}, {"ko": "생경", "en": "Unfamiliarity"}, {"ko": "향수", "en": "Nostalgia"}, {"ko": "동심", "en": "Childlike innocence"}, 
    {"ko": "성숙", "en": "Maturity"}, {"ko": "미성숙", "en": "Immaturity"}, {"ko": "순수", "en": "Purity"}, {"ko": "타락", "en": "Corruption"}, {"ko": "공감", "en": "Empathy"},
    {"ko": "반감", "en": "Antipathy"}, {"ko": "편견", "en": "Prejudice"}, {"ko": "이해", "en": "Understanding"}, {"ko": "애증", "en": "Love-Hate"}, {"ko": "자애", "en": "Benevolence"}, 
    {"ko": "비애", "en": "Sorrow"}, {"ko": "고뇌", "en": "Agony"}, {"ko": "번민", "en": "Anguish"}, {"ko": "집념", "en": "Tenacity"}, {"ko": "염원", "en": "Desire"},
    {"ko": "비장함", "en": "Solemnity"}, {"ko": "비굴함", "en": "Servility"}, {"ko": "오만", "en": "Arrogance"}, {"ko": "겸손", "en": "Humility"}, {"ko": "냉정", "en": "Cool-headedness"}, 
    {"ko": "열띤", "en": "Heated"}, {"ko": "들뜬", "en": "Excited"}, {"ko": "가라앉은", "en": "Subsided"}, {"ko": "먹먹함", "en": "Stifled"}, {"ko": "후련함", "en": "Relieved"},
    {"ko": "찝찝함", "en": "Uncomfortable"}, {"ko": "무안함", "en": "Embarrassed"}, {"ko": "황당함", "en": "Absurdity"}, {"ko": "경멸", "en": "Contempt"}, {"ko": "숭배", "en": "Worship"}, 
    {"ko": "갈채", "en": "Applause"}, {"ko": "야유", "en": "Booing"}, {"ko": "환대", "en": "Hospitality"}, {"ko": "박대", "en": "Mistreatment"}, {"ko": "동질감", "en": "Kinship"},
    {"ko": "이질감", "en": "Heterogeneity"}, {"ko": "열등감", "en": "Inferiority"}, {"ko": "우월감", "en": "Superiority"}, {"ko": "회의감", "en": "Skepticism"}, {"ko": "성취감", "en": "Achievement"}, 
    {"ko": "압도됨", "en": "Overwhelmed"}, {"ko": "홀가분함", "en": "Lighthearted"}, {"ko": "비통함", "en": "Grief"}, {"ko": "달콤함", "en": "Sweetness"}, {"ko": "쓰라림", "en": "Bitterness"},
    {"ko": "씁쓸함", "en": "Bittersweet"}, {"ko": "설움", "en": "Sorrow"}, {"ko": "울화", "en": "Pent-up anger"}, {"ko": "평정심", "en": "Composure"}, {"ko": "광기", "en": "Madness"}, 
    {"ko": "도취", "en": "Intoxication"}, {"ko": "황홀경", "en": "Rapture"}, {"ko": "무아지경", "en": "Trance"}, {"ko": "염세적", "en": "Pessimistic"}, {"ko": "낙천적", "en": "Optimistic"},
    {"ko": "냉혈", "en": "Cold-blooded"}, {"ko": "다정함", "en": "Tenderness"}, {"ko": "냉담함", "en": "Indifference"}, {"ko": "무뚝뚝함", "en": "Bluntness"}, {"ko": "상냥함", "en": "Kindness"}, 
    {"ko": "뻔뻔함", "en": "Shamelessness"}, {"ko": "겸허함", "en": "Modesty"}, {"ko": "당당함", "en": "Confidence"}, {"ko": "위축됨", "en": "Intimidated"}, {"ko": "처량함", "en": "Miserable"},
    {"ko": "죄책감", "en": "Guilt"}, {"ko": "소유욕", "en": "Possessiveness"}, {"ko": "적개심", "en": "Hostility"}, {"ko": "자기혐오", "en": "Self-loathing"}, {"ko": "도덕심", "en": "Morality"}, 
    {"ko": "연대감", "en": "Solidarity"}, {"ko": "무력감", "en": "Helplessness"}, {"ko": "유혹", "en": "Temptation"}, {"ko": "인내심", "en": "Endurance"}, {"ko": "호전성", "en": "Belligerence"},
    {"ko": "방어기제", "en": "Defense mechanism"}, {"ko": "피해의식", "en": "Victim mentality"}, {"ko": "정체성", "en": "Identity"}, {"ko": "자존심", "en": "Self-esteem"}, {"ko": "강박", "en": "Obsession"}, 
    {"ko": "트라우마", "en": "Trauma"}, {"ko": "콤플렉스", "en": "Complex"}, {"ko": "나르시시즘", "en": "Narcissism"}, {"ko": "우애", "en": "Friendship"}, {"ko": "동포애", "en": "Brotherhood"},
    {"ko": "인류애", "en": "Humanity"}, {"ko": "정의감", "en": "Justice"}, {"ko": "사명감", "en": "Sense of duty"}, {"ko": "무심함", "en": "Indifference"}, {"ko": "비정함", "en": "Heartlessness"}, 
    {"ko": "정당함", "en": "Justification"}, {"ko": "억울함", "en": "Injustice"}, {"ko": "비참함", "en": "Misery"}, {"ko": "황량함", "en": "Desolation"}, {"ko": "포근함", "en": "Cozy"},
    {"ko": "상쾌함", "en": "Refreshing"}, {"ko": "뭉클함", "en": "Touching"}, {"ko": "멍함", "en": "Dazed"}, {"ko": "울컥함", "en": "Choked up"}, {"ko": "거만함", "en": "Haughtiness"}, 
    {"ko": "담백함", "en": "Plainness"}, {"ko": "끈기", "en": "Perseverance"}, {"ko": "변덕", "en": "Caprice"}, {"ko": "조울", "en": "Bipolar"}, {"ko": "차분함", "en": "Calmness"},
    {"ko": "막막함", "en": "Hopelessness"}, {"ko": "미안함", "en": "Sorry"}, {"ko": "고마움", "en": "Gratitude"}, {"ko": "쑥스러움", "en": "Bashfulness"}, {"ko": "민망함", "en": "Embarrassed"}, 
    {"ko": "당황스러움", "en": "Perplexed"}, {"ko": "전율", "en": "Thrill"}, {"ko": "다정다감", "en": "Sentimental"},

    # 2. 시간과 공간의 추상적 표현 (200개)
    {"ko": "찰나", "en": "Moment"}, {"ko": "영원", "en": "Eternity"}, {"ko": "과거", "en": "Past"}, {"ko": "미래", "en": "Future"}, {"ko": "현재", "en": "Present"}, 
    {"ko": "새벽", "en": "Dawn"}, {"ko": "황혼", "en": "Twilight"}, {"ko": "정오", "en": "Noon"}, {"ko": "자정", "en": "Midnight"}, {"ko": "심연", "en": "Abyss"},
    {"ko": "우주", "en": "Universe"}, {"ko": "미로", "en": "Maze"}, {"ko": "경계", "en": "Boundary"}, {"ko": "틈새", "en": "Gap"}, {"ko": "통로", "en": "Passage"}, 
    {"ko": "막다른 길", "en": "Dead end"}, {"ko": "시작", "en": "Beginning"}, {"ko": "끝", "en": "End"}, {"ko": "회귀", "en": "Return"}, {"ko": "단절", "en": "Severance"},
    {"ko": "연결", "en": "Connection"}, {"ko": "고립", "en": "Isolation"}, {"ko": "광장", "en": "Plaza"}, {"ko": "골목", "en": "Alley"}, {"ko": "지평선", "en": "Horizon"}, 
    {"ko": "수평선", "en": "Sea horizon"}, {"ko": "궤도", "en": "Orbit"}, {"ko": "차원", "en": "Dimension"}, {"ko": "평행", "en": "Parallel"}, {"ko": "교차", "en": "Intersection"},
    {"ko": "정지", "en": "Stop"}, {"ko": "가속", "en": "Acceleration"}, {"ko": "감속", "en": "Deceleration"}, {"ko": "시대", "en": "Era"}, {"ko": "역사", "en": "History"}, 
    {"ko": "전설", "en": "Legend"}, {"ko": "신화", "en": "Myth"}, {"ko": "기억", "en": "Memory"}, {"ko": "망각", "en": "Oblivion"}, {"ko": "유적", "en": "Ruins"},
    {"ko": "폐허", "en": "Ruins"}, {"ko": "낙원", "en": "Paradise"}, {"ko": "지옥", "en": "Hell"}, {"ko": "안식처", "en": "Sanctuary"}, {"ko": "은신처", "en": "Hideout"}, 
    {"ko": "요새", "en": "Fortress"}, {"ko": "감옥", "en": "Prison"}, {"ko": "창문", "en": "Window"}, {"ko": "거울", "en": "Mirror"}, {"ko": "문턱", "en": "Threshold"},
    {"ko": "계단", "en": "Stairs"}, {"ko": "다리", "en": "Bridge"}, {"ko": "섬", "en": "Island"}, {"ko": "사막", "en": "Desert"}, {"ko": "오아시스", "en": "Oasis"}, 
    {"ko": "빙하", "en": "Glacier"}, {"ko": "화산", "en": "Volcano"}, {"ko": "늪", "en": "Swamp"}, {"ko": "숲", "en": "Forest"}, {"ko": "정원", "en": "Garden"},
    {"ko": "광야", "en": "Wilderness"}, {"ko": "심해", "en": "Deep sea"}, {"ko": "구름 위", "en": "Above clouds"}, {"ko": "별자리", "en": "Constellation"}, {"ko": "은하", "en": "Galaxy"}, 
    {"ko": "블랙홀", "en": "Black hole"}, {"ko": "그림자", "en": "Shadow"}, {"ko": "빛", "en": "Light"}, {"ko": "반사", "en": "Reflection"}, {"ko": "굴절", "en": "Refraction"},
    {"ko": "투영", "en": "Projection"}, {"ko": "허상", "en": "Illusion"}, {"ko": "실체", "en": "Reality"}, {"ko": "신기루", "en": "Mirage"}, {"ko": "환상", "en": "Fantasy"}, 
    {"ko": "현실", "en": "Reality"}, {"ko": "꿈속", "en": "In a dream"}, {"ko": "무의식", "en": "Unconscious"}, {"ko": "의식", "en": "Conscious"}, {"ko": "찰나의 순간", "en": "Fleeting moment"},
    {"ko": "억겁", "en": "Eon"}, {"ko": "계절", "en": "Season"}, {"ko": "봄날", "en": "Spring day"}, {"ko": "한여름", "en": "Midsummer"}, {"ko": "늦가을", "en": "Late autumn"}, 
    {"ko": "엄동설한", "en": "Deep winter"}, {"ko": "세월", "en": "Time"}, {"ko": "흐름", "en": "Flow"}, {"ko": "고임", "en": "Stagnation"}, {"ko": "역류", "en": "Backflow"},
    {"ko": "순행", "en": "Direct motion"}, {"ko": "시계추", "en": "Pendulum"}, {"ko": "모래시계", "en": "Hourglass"}, {"ko": "나이테", "en": "Tree ring"}, {"ko": "흔적", "en": "Trace"}, 
    {"ko": "자국", "en": "Mark"}, {"ko": "잔상", "en": "Afterimage"}, {"ko": "여운", "en": "Lingering imagery"}, {"ko": "궤적", "en": "Trajectory"}, {"ko": "좌표", "en": "Coordinate"},
    {"ko": "방위", "en": "Direction"}, {"ko": "나침반", "en": "Compass"}, {"ko": "지도", "en": "Map"}, {"ko": "항로", "en": "Route"}, {"ko": "여정", "en": "Journey"}, 
    {"ko": "목적지", "en": "Destination"}, {"ko": "출발점", "en": "Starting point"}, {"ko": "안개 속", "en": "In the fog"}, {"ko": "폭풍전야", "en": "Calm before storm"}, {"ko": "만물", "en": "All things"},
    {"ko": "무(無)", "en": "Nothingness"}, {"ko": "진공", "en": "Vacuum"}, {"ko": "압력", "en": "Pressure"}, {"ko": "중력", "en": "Gravity"}, {"ko": "무중력", "en": "Zero gravity"}, 
    {"ko": "부양", "en": "Levitation"}, {"ko": "추락", "en": "Fall"}, {"ko": "침전", "en": "Sedimentation"}, {"ko": "부유", "en": "Floating"}, {"ko": "파동", "en": "Wave"},
    {"ko": "진동", "en": "Vibration"}, {"ko": "파편", "en": "Fragment"}, {"ko": "덩어리", "en": "Chunk"}, {"ko": "구체", "en": "Sphere"}, {"ko": "평면", "en": "Plane"}, 
    {"ko": "입체", "en": "Solid"}, {"ko": "왜곡", "en": "Distortion"}, {"ko": "원형", "en": "Archetype"}, {"ko": "본질", "en": "Essence"}, {"ko": "껍데기", "en": "Shell"},
    {"ko": "심장부", "en": "Core"}, {"ko": "변두리", "en": "Outskirts"}, {"ko": "중심", "en": "Center"}, {"ko": "주변", "en": "Periphery"}, {"ko": "너머", "en": "Beyond"}, 
    {"ko": "저편", "en": "The other side"}, {"ko": "막간", "en": "Interlude"}, {"ko": "시한부", "en": "Terminally ill"}, {"ko": "유통기한", "en": "Expiration date"}, {"ko": "영겁", "en": "Aeon"},
    {"ko": "태초", "en": "Genesis"}, {"ko": "종말", "en": "Apocalypse"}, {"ko": "사후세계", "en": "Afterlife"}, {"ko": "평행우주", "en": "Parallel universe"}, {"ko": "웜홀", "en": "Wormhole"}, 
    {"ko": "미답지", "en": "Unexplored land"}, {"ko": "사각지대", "en": "Blind spot"}, {"ko": "요람", "en": "Cradle"}, {"ko": "무덤", "en": "Grave"}, {"ko": "감옥", "en": "Jail"},
    {"ko": "성역", "en": "Sanctuary"}, {"ko": "금표", "en": "Forbidden mark"}, {"ko": "도심", "en": "Downtown"}, {"ko": "변두리", "en": "Suburbs"}, {"ko": "이정표", "en": "Milestone"}, 
    {"ko": "갈림길", "en": "Crossroads"}, {"ko": "막다른 골목", "en": "Dead end alley"}, {"ko": "수직", "en": "Vertical"}, {"ko": "수평", "en": "Horizontal"}, {"ko": "대각선", "en": "Diagonal"},
    {"ko": "나선", "en": "Spiral"}, {"ko": "소용돌이", "en": "Vortex"}, {"ko": "원점", "en": "Origin"}, {"ko": "반환점", "en": "Turnaround point"}, {"ko": "정점", "en": "Peak"}, 
    {"ko": "바닥", "en": "Bottom"}, {"ko": "구석", "en": "Corner"}, {"ko": "틈바구니", "en": "Cranny"}, {"ko": "허공", "en": "Void"}, {"ko": "대기실", "en": "Waiting room"},
    {"ko": "대합실", "en": "Waiting hall"}, {"ko": "정류장", "en": "Station"}, {"ko": "항구", "en": "Port"}, {"ko": "활주로", "en": "Runway"}, {"ko": "궤도 이탈", "en": "Derailment"}, 
    {"ko": "무풍지대", "en": "Doldrums"}, {"ko": "진앙지", "en": "Epicenter"}, {"ko": "발원지", "en": "Source"}, {"ko": "거점", "en": "Base"}, {"ko": "전초기지", "en": "Outpost"},
    {"ko": "안가", "en": "Safe house"}, {"ko": "밀실", "en": "Secret room"}, {"ko": "광장", "en": "Square"}, {"ko": "가상세계", "en": "Virtual world"}, {"ko": "증강현실", "en": "Augmented reality"}, 
    {"ko": "환상향", "en": "Fantasy land"}, {"ko": "무릉도원", "en": "Peach Blossom Land"}, {"ko": "샹그릴라", "en": "Shangri-La"}, {"ko": "아틀란티스", "en": "Atlantis"}, {"ko": "유토피아", "en": "Utopia"},
    {"ko": "디스토피아", "en": "Dystopia"}, {"ko": "판도라의 상자", "en": "Pandora's box"}, {"ko": "정적", "en": "Silence"}, {"ko": "소음", "en": "Noise"}, {"ko": "비어있는 방", "en": "Empty room"}, 
    {"ko": "붐비는 거리", "en": "Crowded street"}, {"ko": "지하도", "en": "Underpass"}, {"ko": "옥상", "en": "Rooftop"}, {"ko": "발코니", "en": "Balcony"}, {"ko": "간이역", "en": "Way station"},
    {"ko": "선착장", "en": "Dock"}, {"ko": "비행장", "en": "Airfield"}, {"ko": "성지", "en": "Holy ground"}, {"ko": "폐가", "en": "Abandoned house"}, {"ko": "흉가", "en": "Haunted house"}, 
    {"ko": "금지구역", "en": "Restricted area"}, {"ko": "최전방", "en": "Frontline"}, {"ko": "휴전선", "en": "Armistice line"}, {"ko": "국경선", "en": "Border line"}, {"ko": "사선", "en": "Line of fire"},
    {"ko": "구름다리", "en": "Overpass"}, {"ko": "무지개다리", "en": "Rainbow bridge"}, {"ko": "징검다리", "en": "Stepping stone"}, {"ko": "외길", "en": "One way"}, {"ko": "샛길", "en": "Side path"}, 
    {"ko": "지름길", "en": "Shortcut"}, {"ko": "우회로", "en": "Detour"}, {"ko": "전생", "en": "Past life"}, {"ko": "환생", "en": "Reincarnation"}, {"ko": "다중우주", "en": "Multiverse"},
    {"ko": "싱귤래리티", "en": "Singularity"}, {"ko": "화이트홀", "en": "White hole"}, {"ko": "구덩이", "en": "Pit"}, {"ko": "구멍", "en": "Hole"}, {"ko": "동굴", "en": "Cave"}, 
    {"ko": "벼랑", "en": "Cliff"}, {"ko": "절벽", "en": "Precipice"}, {"ko": "비탈길", "en": "Slope"}, {"ko": "터널", "en": "Tunnel"},

    # 3. 자연과 사물의 메타포 (100개)
    {"ko": "가시", "en": "Thorn"}, {"ko": "꽃잎", "en": "Petal"}, {"ko": "뿌리", "en": "Root"}, {"ko": "줄기", "en": "Stem"}, {"ko": "열매", "en": "Fruit"}, 
    {"ko": "씨앗", "en": "Seed"}, {"ko": "고목", "en": "Old tree"}, {"ko": "넝쿨", "en": "Vine"}, {"ko": "이끼", "en": "Moss"}, {"ko": "돋아남", "en": "Sprout"},
    {"ko": "시듦", "en": "Wilt"}, {"ko": "낙엽", "en": "Fallen leaf"}, {"ko": "단풍", "en": "Autumn foliage"}, {"ko": "파도", "en": "Wave"}, {"ko": "물결", "en": "Ripple"}, 
    {"ko": "거품", "en": "Bubble"}, {"ko": "소용돌이", "en": "Whirlpool"}, {"ko": "물방울", "en": "Droplet"}, {"ko": "이슬", "en": "Dew"}, {"ko": "서리", "en": "Frost"},
    {"ko": "눈꽃", "en": "Snowflake"}, {"ko": "우박", "en": "Hail"}, {"ko": "소나기", "en": "Shower"}, {"ko": "가랑비", "en": "Drizzle"}, {"ko": "무지개", "en": "Rainbow"}, 
    {"ko": "번개", "en": "Lightning"}, {"ko": "천둥", "en": "Thunder"}, {"ko": "바람", "en": "Wind"}, {"ko": "돌풍", "en": "Gust"}, {"ko": "미풍", "en": "Breeze"},
    {"ko": "삭풍", "en": "Biting wind"}, {"ko": "흙", "en": "Soil"}, {"ko": "먼지", "en": "Dust"}, {"ko": "모래", "en": "Sand"}, {"ko": "바위", "en": "Rock"}, 
    {"ko": "보석", "en": "Jewel"}, {"ko": "원석", "en": "Gemstone"}, {"ko": "금속", "en": "Metal"}, {"ko": "녹", "en": "Rust"}, {"ko": "화염", "en": "Flame"},
    {"ko": "불꽃", "en": "Spark"}, {"ko": "재", "en": "Ash"}, {"ko": "연기", "en": "Smoke"}, {"ko": "그을음", "en": "Soot"}, {"ko": "태양", "en": "Sun"}, 
    {"ko": "달", "en": "Moon"}, {"ko": "초승달", "en": "Crescent moon"}, {"ko": "그믐달", "en": "Old moon"}, {"ko": "혜성", "en": "Comet"}, {"ko": "유성", "en": "Meteor"},
    {"ko": "성운", "en": "Nebula"}, {"ko": "대기", "en": "Atmosphere"}, {"ko": "산소", "en": "Oxygen"}, {"ko": "향기", "en": "Scent"}, {"ko": "악취", "en": "Stench"}, 
    {"ko": "소리", "en": "Sound"}, {"ko": "소음", "en": "Noise"}, {"ko": "화음", "en": "Harmony"}, {"ko": "불협화음", "en": "Dissonance"}, {"ko": "메아리", "en": "Echo"},
    {"ko": "울림", "en": "Resonance"}, {"ko": "침묵", "en": "Silence"}, {"ko": "깃털", "en": "Feather"}, {"ko": "날개", "en": "Wing"}, {"ko": "부리", "en": "Beak"}, 
    {"ko": "발톱", "en": "Claw"}, {"ko": "비늘", "en": "Scale"}, {"ko": "가죽", "en": "Leather"}, {"ko": "뼈", "en": "Bone"}, {"ko": "껍질", "en": "Shell"},
    {"ko": "고치", "en": "Cocoon"}, {"ko": "나비", "en": "Butterfly"}, {"ko": "벌레", "en": "Bug"}, {"ko": "거미줄", "en": "Spiderweb"}, {"ko": "둥지", "en": "Nest"}, 
    {"ko": "먹이", "en": "Prey"}, {"ko": "포식", "en": "Predation"}, {"ko": "기생", "en": "Parasitism"}, {"ko": "공생", "en": "Symbiosis"}, {"ko": "야생", "en": "Wild"},
    {"ko": "가축", "en": "Livestock"}, {"ko": "길들임", "en": "Taming"}, {"ko": "숲의 속삭임", "en": "Whisper of forest"}, {"ko": "바다의 노래", "en": "Song of sea"}, {"ko": "땅의 울분", "en": "Wrath of earth"}, 
    {"ko": "하늘의 눈물", "en": "Tears of sky"}, {"ko": "구름의 이동", "en": "Movement of clouds"}, {"ko": "안개의 장막", "en": "Veil of fog"}, {"ko": "얼음의 침묵", "en": "Silence of ice"}, {"ko": "불의 춤", "en": "Dance of fire"},
    {"ko": "돌의 인내", "en": "Patience of stone"}, {"ko": "나무의 지혜", "en": "Wisdom of tree"}, {"ko": "강물의 유랑", "en": "Wandering of river"}, {"ko": "산의 침묵", "en": "Silence of mountain"}, {"ko": "들판의 자유", "en": "Freedom of field"}, 
    {"ko": "늪의 유혹", "en": "Lure of swamp"}, {"ko": "사막의 고독", "en": "Solitude of desert"}, {"ko": "동굴의 비밀", "en": "Secret of cave"}, {"ko": "파도의 포말", "en": "Foam of waves"}, {"ko": "숲의 정적", "en": "Stillness of forest"},

    # 4. 인간관계와 사회적 서사 (100개)
    {"ko": "약속", "en": "Promise"}, {"ko": "유언", "en": "Will"}, {"ko": "편지", "en": "Letter"}, {"ko": "고백", "en": "Confession"}, {"ko": "비밀", "en": "Secret"}, 
    {"ko": "소문", "en": "Rumor"}, {"ko": "거짓말", "en": "Lie"}, {"ko": "진실", "en": "Truth"}, {"ko": "가면", "en": "Mask"}, {"ko": "얼굴", "en": "Face"},
    {"ko": "시선", "en": "Gaze"}, {"ko": "손길", "en": "Touch"}, {"ko": "발걸음", "en": "Footstep"}, {"ko": "포옹", "en": "Embrace"}, {"ko": "입맞춤", "en": "Kiss"}, 
    {"ko": "작별", "en": "Farewell"}, {"ko": "만남", "en": "Meeting"}, {"ko": "재회", "en": "Reunion"}, {"ko": "동행", "en": "Companionship"}, {"ko": "경쟁", "en": "Competition"},
    {"ko": "협력", "en": "Cooperation"}, {"ko": "희생", "en": "Sacrifice"}, {"ko": "헌신", "en": "Dedication"}, {"ko": "이기심", "en": "Selfishness"}, {"ko": "배려", "en": "Consideration"}, 
    {"ko": "오해", "en": "Misunderstanding"}, {"ko": "이해", "en": "Understanding"}, {"ko": "관용", "en": "Tolerance"}, {"ko": "복수", "en": "Revenge"}, {"ko": "응징", "en": "Punishment"},
    {"ko": "심판", "en": "Judgment"}, {"ko": "구원", "en": "Salvation"}, {"ko": "타락", "en": "Corruption"}, {"ko": "숭배", "en": "Worship"}, {"ko": "저주", "en": "Curse"}, 
    {"ko": "축복", "en": "Blessing"}, {"ko": "기도", "en": "Prayer"}, {"ko": "마법", "en": "Magic"}, {"ko": "주문", "en": "Spell"}, {"ko": "계약", "en": "Contract"},
    {"ko": "속박", "en": "Bondage"}, {"ko": "해방", "en": "Liberation"}, {"ko": "반역", "en": "Rebellion"}, {"ko": "혁명", "en": "Revolution"}, {"ko": "질서", "en": "Order"}, 
    {"ko": "혼돈", "en": "Chaos"}, {"ko": "법", "en": "Law"}, {"ko": "규칙", "en": "Rule"}, {"ko": "금기", "en": "Taboo"}, {"ko": "전통", "en": "Tradition"},
    {"ko": "혁신", "en": "Innovation"}, {"ko": "계승", "en": "Succession"}, {"ko": "단절", "en": "Disconnection"}, {"ko": "가난", "en": "Poverty"}, {"ko": "풍요", "en": "Abundance"}, 
    {"ko": "전쟁", "en": "War"}, {"ko": "평화", "en": "Peace"}, {"ko": "승리", "en": "Victory"}, {"ko": "패배", "en": "Defeat"}, {"ko": "영광", "en": "Glory"},
    {"ko": "오욕", "en": "Disgrace"}, {"ko": "왕관", "en": "Crown"}, {"ko": "족쇄", "en": "Shackle"}, {"ko": "감시", "en": "Surveillance"}, {"ko": "보호", "en": "Protection"}, 
    {"ko": "추방", "en": "Exile"}, {"ko": "망명", "en": "Asylum"}, {"ko": "귀환", "en": "Return"}, {"ko": "유랑", "en": "Wandering"}, {"ko": "정착", "en": "Settlement"},
    {"ko": "고향", "en": "Hometown"}, {"ko": "타향", "en": "Foreign land"}, {"ko": "우정", "en": "Friendship"}, {"ko": "혈연", "en": "Blood ties"}, {"ko": "연인", "en": "Lover"}, 
    {"ko": "스승", "en": "Teacher"}, {"ko": "제자", "en": "Disciple"}, {"ko": "원수", "en": "Enemy"}, {"ko": "그림자", "en": "Shadow"}, {"ko": "분신", "en": "Alter ego"},
    {"ko": "역할", "en": "Role"}, {"ko": "연극", "en": "Play"}, {"ko": "무대", "en": "Stage"}, {"ko": "관객", "en": "Audience"}, {"ko": "주인공", "en": "Protagonist"}, 
    {"ko": "조연", "en": "Supporting role"}, {"ko": "기록", "en": "Record"}, {"ko": "삭제", "en": "Deletion"}, {"ko": "은폐", "en": "Concealment"}, {"ko": "노출", "en": "Exposure"},
    {"ko": "감금", "en": "Confinement"}, {"ko": "탈출", "en": "Escape"}, {"ko": "미행", "en": "Shadowing"}, {"ko": "추격", "en": "Chase"}, {"ko": "잠입", "en": "Infiltration"}, 
    {"ko": "도주", "en": "Flight"}, {"ko": "매복", "en": "Ambush"}, {"ko": "습격", "en": "Raid"}, {"ko": "방어", "en": "Defense"}, {"ko": "공격", "en": "Attack"},

    # 5. 예술, 철학 및 감각적 상태 (100개)
    {"ko": "추상", "en": "Abstract"}, {"ko": "구상", "en": "Figurative"}, {"ko": "여백", "en": "Negative space"}, {"ko": "채움", "en": "Filling"}, {"ko": "비움", "en": "Emptying"}, 
    {"ko": "질서", "en": "Order"}, {"ko": "무질서", "en": "Disorder"}, {"ko": "조화", "en": "Harmony"}, {"ko": "부조화", "en": "Disharmony"}, {"ko": "균형", "en": "Balance"},
    {"ko": "불균형", "en": "Imbalance"}, {"ko": "대칭", "en": "Symmetry"}, {"ko": "비대칭", "en": "Asymmetry"}, {"ko": "리듬", "en": "Rhythm"}, {"ko": "멜로디", "en": "Melody"}, 
    {"ko": "템포", "en": "Tempo"}, {"ko": "강약", "en": "Dynamics"}, {"ko": "고저", "en": "Pitch"}, {"ko": "음영", "en": "Shade"}, {"ko": "채도", "en": "Saturation"},
    {"ko": "명도", "en": "Brightness"}, {"ko": "농도", "en": "Density"}, {"ko": "밀도", "en": "Density"}, {"ko": "강도", "en": "Intensity"}, {"ko": "경도", "en": "Hardness"}, 
    {"ko": "유연함", "en": "Flexibility"}, {"ko": "딱딱함", "en": "Stiffness"}, {"ko": "부드러움", "en": "Softness"}, {"ko": "거침", "en": "Roughness"}, {"ko": "매끄러움", "en": "Smoothness"},
    {"ko": "날카로운", "en": "Sharp"}, {"ko": "뭉툭함", "en": "Bluntness"}, {"ko": "무거움", "en": "Heaviness"}, {"ko": "가벼움", "en": "Lightness"}, {"ko": "빠름", "en": "Fast"}, 
    {"ko": "느림", "en": "Slow"}, {"ko": "높음", "en": "High"}, {"ko": "낮음", "en": "Low"}, {"ko": "깊음", "en": "Deep"}, {"ko": "얕음", "en": "Shallow"},
    {"ko": "넓음", "en": "Wide"}, {"ko": "좁음", "en": "Narrow"}, {"ko": "밝음", "en": "Bright"}, {"ko": "어두움", "en": "Dark"}, {"ko": "선명함", "en": "Vividness"}, 
    {"ko": "흐릿함", "en": "Blurry"}, {"ko": "왜곡된", "en": "Distorted"}, {"ko": "곧은", "en": "Straight"}, {"ko": "굽은", "en": "Curved"}, {"ko": "꼬인", "en": "Twisted"},
    {"ko": "풀린", "en": "Untangled"}, {"ko": "얽힌", "en": "Entangled"}, {"ko": "흩어진", "en": "Scattered"}, {"ko": "모인", "en": "Gathered"}, {"ko": "솟은", "en": "Soaring"}, 
    {"ko": "꺼진", "en": "Sunken"}, {"ko": "팽창", "en": "Expansion"}, {"ko": "수축", "en": "Contraction"}, {"ko": "폭발", "en": "Explosion"}, {"ko": "함몰", "en": "Collapse"},
    {"ko": "연소", "en": "Combustion"}, {"ko": "냉각", "en": "Cooling"}, {"ko": "응고", "en": "Solidification"}, {"ko": "융해", "en": "Melting"}, {"ko": "증발", "en": "Evaporation"}, 
    {"ko": "승화", "en": "Sublimation"}, {"ko": "순환", "en": "Circulation"}, {"ko": "정체", "en": "Stagnation"}, {"ko": "진화", "en": "Evolution"}, {"ko": "퇴화", "en": "Degeneration"},
    {"ko": "변이", "en": "Mutation"}, {"ko": "복제", "en": "Cloning"}, {"ko": "창조", "en": "Creation"}, {"ko": "파괴", "en": "Destruction"}, {"ko": "모방", "en": "Imitation"}, 
    {"ko": "독창", "en": "Originality"}, {"ko": "고전", "en": "Classic"}, {"ko": "현대", "en": "Modern"}, {"ko": "아방가르드", "en": "Avant-garde"}, {"ko": "키치", "en": "Kitsch"},
    {"ko": "탐미", "en": "Aestheticism"}, {"ko": "숭고미", "en": "Sublime beauty"}, {"ko": "추함", "en": "Ugliness"}, {"ko": "아름다움", "en": "Beauty"}, {"ko": "성스러움", "en": "Holiness"}, 
    {"ko": "속됨", "en": "Vulgarity"}, {"ko": "아이러니", "en": "Irony"}, {"ko": "패러독스", "en": "Paradox"}, {"ko": "은유", "en": "Metaphor"}, {"ko": "직유", "en": "Simile"},
    {"ko": "상징", "en": "Symbol"}, {"ko": "알레고리", "en": "Allegory"}, {"ko": "풍자", "en": "Satire"}, {"ko": "해학", "en": "Humor"}, {"ko": "비극", "en": "Tragedy"}, 
    {"ko": "희극", "en": "Comedy"}, {"ko": "서사", "en": "Narrative"}, {"ko": "서정", "en": "Lyrical"}, {"ko": "낭만", "en": "Romance"}, {"ko": "실존", "en": "Existence"},

    # 6. 행동과 변화의 양상 (100개)
    {"ko": "꿈꾸다", "en": "Dream"}, {"ko": "속이다", "en": "Deceive"}, {"ko": "가리다", "en": "Cover"}, {"ko": "드러내다", "en": "Reveal"}, {"ko": "훔치다", "en": "Steal"}, 
    {"ko": "나누다", "en": "Share"}, {"ko": "합치다", "en": "Combine"}, {"ko": "찢다", "en": "Tear"}, {"ko": "붙이다", "en": "Paste"}, {"ko": "태우다", "en": "Burn"}, 
    {"ko": "얼리다", "en": "Freeze"}, {"ko": "녹이다", "en": "Melt"}, {"ko": "뚫다", "en": "Pierce"}, {"ko": "막다", "en": "Block"}, {"ko": "던지다", "en": "Throw"}, 
    {"ko": "받다", "en": "Receive/Catch"}, {"ko": "밀다", "en": "Push"}, {"ko": "당기다", "en": "Pull"}, {"ko": "오르다", "en": "Climb"}, {"ko": "내리다", "en": "Descend"},
    {"ko": "뛰다", "en": "Run/Jump"}, {"ko": "걷다", "en": "Walk"}, {"ko": "기어가다", "en": "Crawl"}, {"ko": "날다", "en": "Fly"}, {"ko": "헤엄치다", "en": "Swim"}, 
    {"ko": "잠기다", "en": "Submerge"}, {"ko": "떠오르다", "en": "Float/Rise"}, {"ko": "가라앉다", "en": "Sink"}, {"ko": "흔들리다", "en": "Shake"}, {"ko": "멈추다", "en": "Stop"},
    {"ko": "변하다", "en": "Change"}, {"ko": "유지하다", "en": "Maintain"}, {"ko": "깨뜨리다", "en": "Break"}, {"ko": "고치다", "en": "Fix"}, {"ko": "만들다", "en": "Make"}, 
    {"ko": "부수다", "en": "Smash"}, {"ko": "찾다", "en": "Find"}, {"ko": "잃다", "en": "Lose"}, {"ko": "잊다", "en": "Forget"}, {"ko": "기억하다", "en": "Remember"},
    {"ko": "말하다", "en": "Speak"}, {"ko": "듣다", "en": "Listen"}, {"ko": "보다", "en": "See"}, {"ko": "만지다", "en": "Touch"}, {"ko": "느끼다", "en": "Feel"}, 
    {"ko": "생각하다", "en": "Think"}, {"ko": "믿다", "en": "Believe"}, {"ko": "의심하다", "en": "Doubt"}, {"ko": "사랑하다", "en": "Love"}, {"ko": "미워하다", "en": "Hate"},
    {"ko": "싸우다", "en": "Fight"}, {"ko": "화해하다", "en": "Reconcile"}, {"ko": "기다리다", "en": "Wait"}, {"ko": "떠나다", "en": "Leave"}, {"ko": "돌아오다", "en": "Return"}, 
    {"ko": "숨다", "en": "Hide"}, {"ko": "나타나다", "en": "Appear"}, {"ko": "죽다", "en": "Die"}, {"ko": "살다", "en": "Live"}, {"ko": "태어나다", "en": "Born"},
    {"ko": "자라다", "en": "Grow"}, {"ko": "늙다", "en": "Age"}, {"ko": "무너지다", "en": "Collapse"}, {"ko": "세우다", "en": "Build"}, {"ko": "견디다", "en": "Endure"}, 
    {"ko": "포기하다", "en": "Give up"}, {"ko": "시도하다", "en": "Try"}, {"ko": "실패하다", "en": "Fail"}, {"ko": "성공하다", "en": "Succeed"}, {"ko": "배우다", "en": "Learn"},
    {"ko": "가르치다", "en": "Teach"}, {"ko": "돕다", "en": "Help"}, {"ko": "방해하다", "en": "Disturb"}, {"ko": "빌리다", "en": "Borrow"}, {"ko": "갚다", "en": "Repay"}, 
    {"ko": "사다", "en": "Buy"}, {"ko": "팔다", "en": "Sell"}, {"ko": "먹다", "en": "Eat"}, {"ko": "마시다", "en": "Drink"}, {"ko": "자다", "en": "Sleep"},
    {"ko": "깨다", "en": "Wake"}, {"ko": "울다", "en": "Cry"}, {"ko": "웃다", "en": "Laugh"}, {"ko": "노래하다", "en": "Sing"}, {"ko": "춤추다", "en": "Dance"}, 
    {"ko": "연주하다", "en": "Play (instrument)"}, {"ko": "그리다", "en": "Draw"}, {"ko": "쓰다", "en": "Write/Use"}, {"ko": "읽다", "en": "Read"}, {"ko": "걷다", "en": "Walk"},
    {"ko": "달리다", "en": "Run"}, {"ko": "서다", "en": "Stand"}, {"ko": "앉다", "en": "Sit"}, {"ko": "눕다", "en": "Lie down"}, {"ko": "기대다", "en": "Lean"}, 
    {"ko": "안다", "en": "Hug"}, {"ko": "업다", "en": "Carry on back"}, {"ko": "잡다", "en": "Hold"}, {"ko": "놓다", "en": "Let go"}, {"ko": "쥐다", "en": "Grasp"},

    # 7. 현대적 일상과 디지털 코드 (100개)
    {"ko": "알고리즘", "en": "Algorithm"}, {"ko": "배터리 1%", "en": "1% Battery"}, {"ko": "로딩 중", "en": "Loading..."}, {"ko": "블루스크린", "en": "Blue Screen"}, {"ko": "필터링", "en": "Filtering"}, 
    {"ko": "해시태그", "en": "Hashtag"}, {"ko": "언박싱", "en": "Unboxing"}, {"ko": "좋아요", "en": "Like"}, {"ko": "스와이프", "en": "Swipe"}, {"ko": "스크롤", "en": "Scroll"},
    {"ko": "하이퍼링크", "en": "Hyperlink"}, {"ko": "팝업창", "en": "Popup"}, {"ko": "다크모드", "en": "Dark Mode"}, {"ko": "와이파이", "en": "Wi-Fi"}, {"ko": "핫스팟", "en": "Hotspot"}, 
    {"ko": "클라우드", "en": "Cloud"}, {"ko": "에어드랍", "en": "AirDrop"}, {"ko": "익명성", "en": "Anonymity"}, {"ko": "가상화폐", "en": "Cryptocurrency"}, {"ko": "메타버스", "en": "Metaverse"},
    {"ko": "아바타", "en": "Avatar"}, {"ko": "증강현실", "en": "AR"}, {"ko": "인공지능", "en": "AI"}, {"ko": "챗봇", "en": "Chatbot"}, {"ko": "갓생", "en": "God-life"}, 
    {"ko": "오운완", "en": "Workout Complete"}, {"ko": "루틴", "en": "Routine"}, {"ko": "번아웃", "en": "Burnout"}, {"ko": "퇴사", "en": "Resignation"}, {"ko": "취준생", "en": "Job Seeker"},
    {"ko": "무지출 챌린지", "en": "No-spend Challenge"}, {"ko": "플렉스", "en": "Flex"}, {"ko": "소확행", "en": "Small Happiness"}, {"ko": "가심비", "en": "Price-satisfaction ratio"}, {"ko": "가성비", "en": "Cost-effectiveness"}, 
    {"ko": "제로 칼로리", "en": "Zero Calorie"}, {"ko": "편의점 도시락", "en": "Convenience Store Bento"}, {"ko": "새벽 배송", "en": "Dawn Delivery"}, {"ko": "1인 가구", "en": "Single Household"}, {"ko": "혼밥", "en": "Eating Alone"},
    {"ko": "고독사", "en": "Lonely Death"}, {"ko": "욜로", "en": "YOLO"}, {"ko": "파이어족", "en": "FIRE Movement"}, {"ko": "주식 그래프", "en": "Stock Graph"}, {"ko": "비트코인", "en": "Bitcoin"}, 
    {"ko": "상한가", "en": "Upper Limit Price"}, {"ko": "하한가", "en": "Lower Limit Price"}, {"ko": "스마트 도어락", "en": "Smart Door Lock"}, {"ko": "CCTV", "en": "CCTV"}, {"ko": "QR코드", "en": "QR Code"},
    {"ko": "스팸 메일", "en": "Spam Mail"}, {"ko": "실시간 검색어", "en": "Real-time Search Terms"}, {"ko": "브이로그", "en": "Vlog"}, {"ko": "입덕", "en": "Becoming a Fan"}, {"ko": "탈덕", "en": "Leaving Fandom"}, 
    {"ko": "성덕", "en": "Successful Fan"}, {"ko": "굿즈", "en": "Merch"}, {"ko": "팝업스토어", "en": "Popup Store"}, {"ko": "오픈런", "en": "Open Run"}, {"ko": "품절 대란", "en": "Sold-out Crisis"},
    {"ko": "리셀", "en": "Resell"}, {"ko": "명품 로고", "en": "Luxury Logo"}, {"ko": "어그로", "en": "Aggro/Trolling"}, {"ko": "팩트폭격", "en": "Fact Bomb"}, {"ko": "뇌절", "en": "Overdoing it"}, 
    {"ko": "손절", "en": "Cut off"}, {"ko": "가스라이팅", "en": "Gaslighting"}, {"ko": "자존감 뿜뿜", "en": "Boiling Self-esteem"}, {"ko": "번개 모임", "en": "Impromptu Meetup"}, {"ko": "불금", "en": "Fire Friday"},
    {"ko": "월요병", "en": "Monday Blues"}, {"ko": "재택근무", "en": "Remote Work"}, {"ko": "비대면", "en": "Contactless"}, {"ko": "랜선 연애", "en": "Online Dating"}, {"ko": "홈트레이닝", "en": "Home Training"}, 
    {"ko": "에코백", "en": "Eco Bag"}, {"ko": "제로 웨이스트", "en": "Zero Waste"}, {"ko": "젠트리피케이션", "en": "Gentrification"}, {"ko": "공유 경제", "en": "Sharing Economy"}, {"ko": "마감 임박", "en": "Deadline Approaching"},
    {"ko": "한정판", "en": "Limited Edition"}, {"ko": "블랙 프라이데이", "en": "Black Friday"}, {"ko": "알림 지옥", "en": "Notification Hell"}, {"ko": "넷플릭스 앤 칠", "en": "Netflix and Chill"}, {"ko": "스트리밍", "en": "Streaming"}, 
    {"ko": "구독 서비스", "en": "Subscription Service"}, {"ko": "타임라인", "en": "Timeline"}, {"ko": "스포일러", "en": "Spoiler"}, {"ko": "쿠키 영상", "en": "Post-credits Scene"}, {"ko": "멀티 페르소나", "en": "Multi-persona"},
    {"ko": "프로필 사진", "en": "Profile Picture"}, {"ko": "상태 메시지", "en": "Status Message"}, {"ko": "유령 메시지", "en": "Ghost Message"}, {"ko": "읽음 사라짐", "en": "Read Receipt"}, {"ko": "잊혀질 권리", "en": "Right to be Forgotten"}, 
    {"ko": "디지털 포렌식", "en": "Digital Forensic"}, {"ko": "딥페이크", "en": "Deepfake"}, {"ko": "사이버 렉카", "en": "Cyber Wrecker"}, {"ko": "도파민", "en": "Dopamine"}, {"ko": "블로그", "en": "Blog"},

    # 8. 형용사적 감각과 질감 (100개)
    {"ko": "폭신한", "en": "Fluffy"}, {"ko": "까칠한", "en": "Rough/Prickly"}, {"ko": "차가운", "en": "Cold"}, {"ko": "뜨거운", "en": "Hot"}, {"ko": "미끈거리는", "en": "Slippery"}, 
    {"ko": "끈적이는", "en": "Sticky"}, {"ko": "단단한", "en": "Hard"}, {"ko": "무른", "en": "Soft"}, {"ko": "바스라지는", "en": "Crumbly"}, {"ko": "투명한", "en": "Transparent"},
    {"ko": "탁한", "en": "Murky"}, {"ko": "선명한", "en": "Vivid"}, {"ko": "흐릿한", "en": "Blurry"}, {"ko": "번지는", "en": "Smudged"}, {"ko": "스며드는", "en": "Permeating"}, 
    {"ko": "튕겨 나가는", "en": "Bouncing off"}, {"ko": "묵직한", "en": "Heavy"}, {"ko": "깃털 같은", "en": "Feathery"}, {"ko": "서늘한", "en": "Chilly"}, {"ko": "눅눅한", "en": "Damp"},
    {"ko": "건조한", "en": "Dry"}, {"ko": "매끄러운", "en": "Smooth"}, {"ko": "투박한", "en": "Crude"}, {"ko": "날카로운", "en": "Sharp"}, {"ko": "뭉툭함", "en": "Blunt"}, 
    {"ko": "일렁이는", "en": "Wavy"}, {"ko": "고정된", "en": "Fixed"}, {"ko": "흔들리는", "en": "Shaking"}, {"ko": "아련한", "en": "Faint/Nostalgic"}, {"ko": "강렬한", "en": "Intense"},
    {"ko": "은은한", "en": "Subtle"}, {"ko": "몽환적인", "en": "Dreamy"}, {"ko": "기괴한", "en": "Grotesque"}, {"ko": "성스러운", "en": "Holy"}, {"ko": "우아한", "en": "Elegant"}, 
    {"ko": "촌스러운", "en": "Tacky"}, {"ko": "화려한", "en": "Fancy"}, {"ko": "소박한", "en": "Simple"}, {"ko": "낡은", "en": "Old/Worn"}, {"ko": "새것의", "en": "Brand new"},
    {"ko": "반짝이는", "en": "Sparkling"}, {"ko": "녹슨", "en": "Rusty"}, {"ko": "축축한", "en": "Wet"}, {"ko": "보송보송한", "en": "Soft/Dry"}, {"ko": "아슬아슬한", "en": "Risky"}, 
    {"ko": "견고한", "en": "Solid"}, {"ko": "허술한", "en": "Shabby"}, {"ko": "촘촘한", "en": "Dense"}, {"ko": "느슨한", "en": "Loose"}, {"ko": "빽빽한", "en": "Packed"},
    {"ko": "텅 빈", "en": "Empty"}, {"ko": "가득 찬", "en": "Full"}, {"ko": "무거운", "en": "Heavy"}, {"ko": "가벼운", "en": "Light"}, {"ko": "빠른", "en": "Fast"}, 
    {"ko": "느림", "en": "Slow"}, {"ko": "깊은", "en": "Deep"}, {"ko": "얕은", "en": "Shallow"}, {"ko": "넓은", "en": "Wide"}, {"ko": "좁은", "en": "Narrow"},
    {"ko": "높은", "en": "High"}, {"ko": "낮은", "en": "Low"}, {"ko": "긴", "en": "Long"}, {"ko": "짧은", "en": "Short"}, {"ko": "둥근", "en": "Round"}, 
    {"ko": "각진", "en": "Angular"}, {"ko": "비뚤어진", "en": "Crooked"}, {"ko": "곧은", "en": "Straight"}, {"ko": "일그러진", "en": "Distorted"}, {"ko": "조화로운", "en": "Harmonious"},
    {"ko": "불협화음의", "en": "Dissonant"}, {"ko": "향기로운", "en": "Fragrant"}, {"ko": "악취 나는", "en": "Stinky"}, {"ko": "달콤한", "en": "Sweet"}, {"ko": "쓴", "en": "Bitter"}, 
    {"ko": "짠", "en": "Salty"}, {"ko": "신", "en": "Sour"}, {"ko": "매운", "en": "Spicy"}, {"ko": "밋밋한", "en": "Bland"}, {"ko": "자극적인", "en": "Stimulating"},
    {"ko": "시끄러운", "en": "Noisy"}, {"ko": "조용한", "en": "Quiet"}, {"ko": "웅장한", "en": "Grand"}, {"ko": "왜소한", "en": "Tiny"}, {"ko": "신비로운", "en": "Mysterious"}, 
    {"ko": "공포스러운", "en": "Terrifying"}, {"ko": "따스한", "en": "Warm"}, {"ko": "냉혹한", "en": "Cold-hearted"}, {"ko": "비정한", "en": "Heartless"}, {"ko": "자비로운", "en": "Merciful"},
    {"ko": "거대한", "en": "Huge"}, {"ko": "미세한", "en": "Tiny"}, {"ko": "복잡한", "en": "Complex"}, {"ko": "단순한", "en": "Simple"}, {"ko": "원색적인", "en": "Primary colorful"}, 
    {"ko": "무채색의", "en": "Achromatic"}, {"ko": "따끔한", "en": "Prickly"}, {"ko": "가려운", "en": "Itchy"}, {"ko": "얼얼한", "en": "Numbing"}, {"ko": "아릿한", "en": "Tingling"}]